// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/proto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidReply_Ack int32

const (
	BidReply_FAIL      BidReply_Ack = 0
	BidReply_SUCCESS   BidReply_Ack = 1
	BidReply_EXCEPTION BidReply_Ack = 2
)

// Enum value maps for BidReply_Ack.
var (
	BidReply_Ack_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
	}
	BidReply_Ack_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
	}
)

func (x BidReply_Ack) Enum() *BidReply_Ack {
	p := new(BidReply_Ack)
	*p = x
	return p
}

func (x BidReply_Ack) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidReply_Ack) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_proto_enumTypes[0].Descriptor()
}

func (BidReply_Ack) Type() protoreflect.EnumType {
	return &file_grpc_proto_proto_enumTypes[0]
}

func (x BidReply_Ack) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidReply_Ack.Descriptor instead.
func (BidReply_Ack) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1, 0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           BidReply_Ack           `protobuf:"varint,1,opt,name=ack,proto3,enum=proto.BidReply_Ack" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidReply) Reset() {
	*x = BidReply{}
	mi := &file_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidReply) ProtoMessage() {}

func (x *BidReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidReply.ProtoReflect.Descriptor instead.
func (*BidReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidReply) GetAck() BidReply_Ack {
	if x != nil {
		return x.Ack
	}
	return BidReply_FAIL
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{2}
}

type ResultReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int32                  `protobuf:"varint,1,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	AuctionOver   bool                   `protobuf:"varint,2,opt,name=auctionOver,proto3" json:"auctionOver,omitempty"`
	Winner        string                 `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultReply) Reset() {
	*x = ResultReply{}
	mi := &file_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultReply) ProtoMessage() {}

func (x *ResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultReply.ProtoReflect.Descriptor instead.
func (*ResultReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ResultReply) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ResultReply) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

func (x *ResultReply) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type ReplicaBidState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int32                  `protobuf:"varint,1,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	AuctionOver   bool                   `protobuf:"varint,2,opt,name=auctionOver,proto3" json:"auctionOver,omitempty"`
	Winner        string                 `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaBidState) Reset() {
	*x = ReplicaBidState{}
	mi := &file_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaBidState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaBidState) ProtoMessage() {}

func (x *ReplicaBidState) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaBidState.ProtoReflect.Descriptor instead.
func (*ReplicaBidState) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaBidState) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicaBidState) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

func (x *ReplicaBidState) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type ReplicaAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaAck) Reset() {
	*x = ReplicaAck{}
	mi := &file_grpc_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaAck) ProtoMessage() {}

func (x *ReplicaAck) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaAck.ProtoReflect.Descriptor instead.
func (*ReplicaAck) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicaAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_grpc_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{6}
}

type SyncReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int32                  `protobuf:"varint,1,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	AuctionOver   bool                   `protobuf:"varint,2,opt,name=auctionOver,proto3" json:"auctionOver,omitempty"`
	Winner        string                 `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncReply) Reset() {
	*x = SyncReply{}
	mi := &file_grpc_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReply) ProtoMessage() {}

func (x *SyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReply.ProtoReflect.Descriptor instead.
func (*SyncReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{7}
}

func (x *SyncReply) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *SyncReply) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

func (x *SyncReply) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

var File_grpc_proto_proto protoreflect.FileDescriptor

const file_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x10grpc/proto.proto\x12\x05proto\"$\n" +
	"\n" +
	"BidRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"^\n" +
	"\bBidReply\x12%\n" +
	"\x03ack\x18\x01 \x01(\x0e2\x13.proto.BidReply.AckR\x03ack\"+\n" +
	"\x03Ack\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02\"\x0f\n" +
	"\rResultRequest\"g\n" +
	"\vResultReply\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x01 \x01(\x05R\n" +
	"highestBid\x12 \n" +
	"\vauctionOver\x18\x02 \x01(\bR\vauctionOver\x12\x16\n" +
	"\x06winner\x18\x03 \x01(\tR\x06winner\"k\n" +
	"\x0fReplicaBidState\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x01 \x01(\x05R\n" +
	"highestBid\x12 \n" +
	"\vauctionOver\x18\x02 \x01(\bR\vauctionOver\x12\x16\n" +
	"\x06winner\x18\x03 \x01(\tR\x06winner\"\x1c\n" +
	"\n" +
	"ReplicaAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\r\n" +
	"\vSyncRequest\"e\n" +
	"\tSyncReply\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x01 \x01(\x05R\n" +
	"highestBid\x12 \n" +
	"\vauctionOver\x18\x02 \x01(\bR\vauctionOver\x12\x16\n" +
	"\x06winner\x18\x03 \x01(\tR\x06winner2h\n" +
	"\aAuction\x12)\n" +
	"\x03Bid\x12\x11.proto.BidRequest\x1a\x0f.proto.BidReply\x122\n" +
	"\x06Result\x12\x14.proto.ResultRequest\x1a\x12.proto.ResultReply2w\n" +
	"\aReplica\x129\n" +
	"\fReplicateBid\x12\x16.proto.ReplicaBidState\x1a\x11.proto.ReplicaAck\x121\n" +
	"\tSyncState\x12\x12.proto.SyncRequest\x1a\x10.proto.SyncReplyB\x1bZ\x19Mandatory-Activity-5/grpcb\x06proto3"

var (
	file_grpc_proto_proto_rawDescOnce sync.Once
	file_grpc_proto_proto_rawDescData []byte
)

func file_grpc_proto_proto_rawDescGZIP() []byte {
	file_grpc_proto_proto_rawDescOnce.Do(func() {
		file_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)))
	})
	return file_grpc_proto_proto_rawDescData
}

var file_grpc_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_proto_proto_goTypes = []any{
	(BidReply_Ack)(0),       // 0: proto.BidReply.Ack
	(*BidRequest)(nil),      // 1: proto.BidRequest
	(*BidReply)(nil),        // 2: proto.BidReply
	(*ResultRequest)(nil),   // 3: proto.ResultRequest
	(*ResultReply)(nil),     // 4: proto.ResultReply
	(*ReplicaBidState)(nil), // 5: proto.ReplicaBidState
	(*ReplicaAck)(nil),      // 6: proto.ReplicaAck
	(*SyncRequest)(nil),     // 7: proto.SyncRequest
	(*SyncReply)(nil),       // 8: proto.SyncReply
}
var file_grpc_proto_proto_depIdxs = []int32{
	0, // 0: proto.BidReply.ack:type_name -> proto.BidReply.Ack
	1, // 1: proto.Auction.Bid:input_type -> proto.BidRequest
	3, // 2: proto.Auction.Result:input_type -> proto.ResultRequest
	5, // 3: proto.Replica.ReplicateBid:input_type -> proto.ReplicaBidState
	7, // 4: proto.Replica.SyncState:input_type -> proto.SyncRequest
	2, // 5: proto.Auction.Bid:output_type -> proto.BidReply
	4, // 6: proto.Auction.Result:output_type -> proto.ResultReply
	6, // 7: proto.Replica.ReplicateBid:output_type -> proto.ReplicaAck
	8, // 8: proto.Replica.SyncState:output_type -> proto.SyncReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_proto_init() }
func file_grpc_proto_proto_init() {
	if File_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_proto_proto_goTypes,
		DependencyIndexes: file_grpc_proto_proto_depIdxs,
		EnumInfos:         file_grpc_proto_proto_enumTypes,
		MessageInfos:      file_grpc_proto_proto_msgTypes,
	}.Build()
	File_grpc_proto_proto = out.File
	file_grpc_proto_proto_goTypes = nil
	file_grpc_proto_proto_depIdxs = nil
}
